export const SHOP_STATE_KEY = '@shop';
export const CLOSE_SHOP_DIALOG = `${SHOP_STATE_KEY}/CLOSE_DIALOG`;
export const OPEN_SHOP_DIALOG = `${SHOP_STATE_KEY}/OPEN_DIALOG`;
export const USER_INITIALIZED = `${SHOP_STATE_KEY}/USER_INITIALIZED`;
export const UPDATE_SHOP_USER = `${SHOP_STATE_KEY}/UPDATE_USER`;
export const UPDATE_SHOP_USER_TYPE = `${SHOP_STATE_KEY}/UPDATE_USER_TYPE`;
export const UPDATE_USER_LOCATION_DATA = `${SHOP_STATE_KEY}/UPDATE_USER_LOCATION_DATA`;
export const UPDATE_SHARED_DATA = `${SHOP_STATE_KEY}/UPDATE_SHARED_DATA`;

export const CART_DIALOG_ROOT_ID = 'cart-dialog-root';

export const ON_FETCH_START = `${SHOP_STATE_KEY}/ON_FETCH_START`;
export const ON_FETCH_FAILURE = `${SHOP_STATE_KEY}/ON_FETCH_FAILURE`;

export const ON_FULFILLMENT_OFFERINGS_SUCCESS = `${SHOP_STATE_KEY}/ON_FULFILLMENT_OFFERINGS_SUCCESS`;
export const ON_SHIPPING_OPTIONS_SUCCESS = `${SHOP_STATE_KEY}/ON_SHIPPING_OPTIONS_SUCCESS`;
export const UPDATE_ENTITIES = `${SHOP_STATE_KEY}/UPDATE_ENTITIES`;
export const CLEAR_NORMALIZED_DATA = `${SHOP_STATE_KEY}/CLEAR_NORMALIZED_DATA`;
export const CLEAR_ERRORS = `${SHOP_STATE_KEY}/CLEAR_ERRORS`;

export const LOCATION_TYPES = {
    digital: 'DIGITAL',
    pickupLocations: 'PICK_UP_LOCATIONS',
    pickupPoints: 'PICKUP_POINTS',
    search: 'SEARCH',
    shipping: 'SHIPPING',
    store: 'STORE_VIEWS',
    pickup: 'PICKUP',
    ship: 'SHIP',
};

export const FETCH_IDENTITY_DATA = `${SHOP_STATE_KEY}/FETCH_IDENTITY_DATA`;
export const FETCH_IDENTITY_DATA_FAILURE = `${SHOP_STATE_KEY}/FETCH_IDENTITY_DATA_FAILURE`;
export const FETCH_IDENTITY_DATA_SUCCESS = `${SHOP_STATE_KEY}/FETCH_IDENTITY_DATA_SUCCESS`;
export const CLEAR_IDENTITY_DATA = `${SHOP_STATE_KEY}/CLEAR_IDENTITY_DATA`;

export const DEFAULT_GRAND_TIMEOUT = 30000;

export const BUY_PARTNER_CART_REVIEWS = 'buy/partner_cart_reviews/v1';

export const DOTCOM_CHANNEL_ID = 'd9a5bc42-4b9c-4976-858a-f159cf99c647';

export const GRAPHQL_ERROR_CODE = 'GRAPHQL_ERROR';

export const FULFILLMENT_OFFERINGS_SEARCH_RADIUS = 50;
